### ISSUE TITLE
consider disabling all repos per default

### ISSUE THREAD

**Issue by goern** [sclorg/rhscl-dockerfiles#5]
Hi there, as I build images with my personal subscription, it pulls in a lot of stuff from repos I dont really want. To normalize the behavior on `docker build` please consider using `yum-config-manager --disable \*` before enabling any rhscl repos.

**Comment by hhorak** [comment]
Thanks for the suggestion, it seems to be a good idea. It shouldn't have any side effects, which we'd find anyway by having missing packages.

**Comment by hhorak** [comment]
Actually it has some side effects, since there are no dependencies between repos, so when we disable all first and just enable rhscl repo, then we miss repos that are already available in base image.

@goern one more thing I don't understand, if you only enable specific repos, how come it pulls in a lot of stuff from other repos? Only repos from base image and specifically enabled repos from the layered image should be enabled.

**Comment by goern** [comment]
some repos might get pulled in from the subscription you use on the host: as a Red Hat employee I have access to many repos you normally dont want in your container images: EUS, HTB, ... these repos are enabled on the host and will be enabled in the container (during build). 

I most often use:
```
RUN yum install -y yum-utils && \
    yum-config-manager --disable \* && \
    yum-config-manager --enable rhel-7-server-rpms && \
    yum-config-manager --enable rhel-7-server-extras-rpms && \
    yum-config-manager --enable rhel-7-server-optional-rpms && \
    yum-config-manager --enable rhel-server-rhscl-7-rpms
...
```

So that all is reset to the basics a container needs, plus SCL and whatever should be enabled...

**Comment by hhorak** [comment]
Sorry, this repos was made deprecated. If the issue is still in place in some of the container under https://github.com/sclorg?q=-container, then, please, report an issue for the specific container image.
